### ISSUE TITLE
Design the sender policy framework SPF for Open edX 

### ISSUE THREAD

**Issue by travula** [openedx-vlead/college-cloud#15]
The design for setting sender policy framework for Open edX platform should be in place.  

@sivashankerN, please include this as part of requirement.

**Comment by ashay-maheshwari** [comment]
This is not related with College cloud edx because of being in offline mode. 
Opening this issue on vlabs.ac.in - https://github.com/openedx-vlead/port-labs-to-openedx/issues/42
