### ISSUE TITLE
Media server to be installed and videos to be served as part of the college cloud

### ISSUE THREAD

**Issue by sivashankerN** [openedx-vlead/college-cloud#20]
In college cloud, There are some labs which are having videos , These videos are loading from Internet. As we know College cloud Edition dose not have Internet, because of this,no videos will be running in college cloud.

We should be able to load videos from College Cloud Edition itself. We have to figure it out.

**Comment by sivashankerN** [comment]
I see one problem here in this,

1. URLs of Videos hosted on production and Videos hosted on College Cloud Edition. 
2. If there is an update in updating URL of Videos hosted on Production and URLs, again we have to download that video and put it in college cloud.  Then the video URL may change again in college cloud. Here, again we have to modify the video URLs manually.

My point is , There is no sync of video urls of Production and College Cloud Edition

**Comment by ashay-maheshwari** [comment]
Discussion on call, dated Fe 21, 2017 -
Attendees - Siva and Ashay

**Discussion** 
Need to identify and count the videos to be served from College Cloud and get the source of videos. Videos can be served using HTML5 embed tag which can be a quick fix to the problem, without the need to explore much of the new technologies and media server available. Following are the suggestions 

**Use HTML5 to server videos locally**
Steps are -
- Identify the source of videos and download and save them in folder 
- Server videos using Apache webserver
- Change the URL of videos to point to right location from where videos are to be served.
- Use HTML 5 to embed video source locally

Benefits are -
- Quick fix if it works 
- Need no new exploration and service to move ahead.
- With a few number of videos (say below 50), this is a good option for now.

**Use media servers**

- Use RED5 or Wowza can be used to stream videos 
- Disadvantage of exploring and running an external service to support these servers. 
- As recommended, these must not be running in containers, hence can result in extra load in college cloud host, or can ask for a separate server.
- Will be time consuming and need some quality time applied to see desired results.

**Use Physical Media server**

- Adds to the cost of College Cloud altogether.
- Needs another Physical device to be added with the product 
- Needs good amount of time to explore


**Based on the discussion, following are the action items -**

1. Explore the option of HTML 5
2. Get the sources of videos and download and save them locally
3. Figure a way out to replace URLs (grep and replace should help)
