### ISSUE TITLE
Theming college cloud for Media Server

### ISSUE THREAD

**Issue by vleadadmin** [openedx-vlead/college-cloud#23]
Theme for College Cloud edx has to be changed so that, we can include NPTEL videos server from media server. This can be done by applying the theme as which is applied on vlabs.ac.in landing page.

**Comment by ashay-maheshwari** [comment]
Theme for College cloud will have custom html pages. Theme is available here - https://github.com/openedx-vlead/vlabs-theme-for-college-cloud

**Comment by ashay-maheshwari** [comment]
Issues and details respective to this are now captured - https://github.com/openedx-vlead/vlabs-theme-for-college-cloud/milestone/1
