### ISSUE TITLE
Identify the videos to be served from College Cloud

### ISSUE THREAD

**Issue by ashay-maheshwari** [openedx-vlead/college-cloud#24]
Identify the videos which are to be served from College Cloud. This includes the following -
1. Get the count of videos NPTEL + videos inside the labs
2. Identify the source of Videos. (Most of them are youtube videos)
3. Download all videos and name them properly if needed.
4. Change the URLs to point to the right video file saved locally.

**Comment by ashay-maheshwari** [comment]
Update the list of videos (NPTEL + Videos inside the labs) Share the link of document

**Comment by sivashankerN** [comment]
https://docs.google.com/spreadsheets/d/1JqfF2s-6fRXP6c4A_pR7m28abVQp6p2-WQiPSaYUPMo/edit?ts=58b7c0f6#gid=0
