### ISSUE TITLE
Download videos to be served from College Cloud

### ISSUE THREAD

**Issue by ashay-maheshwari** [openedx-vlead/college-cloud#27]
- Prepare a list of videos (NPTEL + videos inside labs) with URL, name of lab and experiment name.
- Refer the list to download videos.
- Youtube videos can be downloaded using YTD or Downloadhelper.
- If video is served other than youtube, Downloadhelper is likely to work.

**Comment by sivashankerN** [comment]
List of Video links  are updated in spreadsheet https://docs.google.com/spreadsheets/d/1JqfF2s-6fRXP6c4A_pR7m28abVQp6p2-WQiPSaYUPMo/edit?ts=58b7c0f6#gid=0
