### ISSUE TITLE
Check the process flow with Syncthing implemented in College Cloud Edition

### ISSUE THREAD

**Issue by ashay-maheshwari** [openedx-vlead/college-cloud#37]
Based on Exploring Syncthing for college cloud - #10 , syncthing was tested and identified to be functioning  to share files between Syncthing client and server. This approves it to be working. 

The intention now is to be integrate Syncthing with College  Cloud and check the process follow - 1
1. Perform some experiments and generate analytics 
2. Fill up some feedback forms
3. Run the script to college logs
4. Syncthing should take the output log file generated by script and must upload it to Central Server under VLEAD.

**Comment by kraghupathi** [comment]
Follow the below documents for syncthing.

1. [Install and setup syncthing](https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/syncthing/index.org)
2. [User-manual](https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/syncthing/user-manual.org)

**Comment by sivashankerN** [comment]
We have tested in MJCET and also in the College Cloud workshop.

It i working , so resolving this issue
